# This file contains field descriptions for selected astronomical catalogs
# Related to Wolf-Rayet stars, MK classifications, LMC, SMC, Gaia, and spectroscopy.
# Generated automatically

catalogs = ['SIMBAD','B_MK','III_276','J_AJ_152_62','J_MNRAS_411_263','III_218','III_230','I_355_GAIADR3','III_47','III_284','III_76','III_135A']

SIMBAD = {
    'bibcodelist(y1-y2)': 'List of bibliographic references (by bibcode) for the object within a given year range',
    'biblio': 'Bibliography of references related to the object',
    'cel': 'Celestial reference data for the object (rarely used)',
    'cl.g': 'Object classification group code',
    'coo(opt)': 'Object coordinates in an optional format/system',
    'coo_bibcode': 'Bibcode of the reference from which the coordinates were obtained',
    'coo_err_angle': 'Angular error of the coordinate uncertainty ellipse',
    'coo_err_maja': 'Major axis length of the coordinate error ellipse',
    'coo_err_mina': 'Minor axis length of the coordinate error ellipse',
    'coo_qual': 'Quality flag for the coordinates',
    'coo_wavelength': 'Wavelength domain in which the coordinates were measured',
    'coordinates': 'ICRS coordinates (Right Ascension and Declination) of the object',
    'dec(opt)': 'Declination in an optional format',
    'dec_prec': 'Precision level of the Declination coordinate',
    'diameter': 'Angular diameter of the object',
    'dim': 'General dimension measurement of the object',
    'dim_angle': 'Position angle of the object’s major axis',
    'dim_bibcode': 'Bibcode of the reference from which dimensions were derived',
    'dim_incl': 'Inclination angle of the object',
    'dim_majaxis': 'Length of the major axis of the object’s dimension',
    'dim_minaxis': 'Length of the minor axis of the object’s dimension',
    'dim_qual': 'Quality flag for the dimension measurement',
    'dim_wavelength': 'Wavelength domain at which the dimension was measured',
    'dimensions': 'All available dimension measurements of the object',
    'distance': 'Distance to the object',
    'distance_result': 'Computed or derived distance result for the object',
    'einstein': 'Cross-identification or data related to EINSTEIN X-ray mission sources',
    'fe_h': 'Metallicity indicator [Fe/H] for the object',
    'flux(filtername)': 'Photometric flux in the specified filter',
    'flux_bibcode(filtername)': 'Reference (bibcode) for the flux measurement in that filter',
    'flux_error(filtername)': 'Error in the flux measurement for that filter',
    'flux_name(filtername)': 'Name or identifier of the flux measurement/filter',
    'flux_qual(filtername)': 'Quality flag for the flux measurement in that filter',
    'flux_system(filtername)': 'Photometric system used for the flux measurement',
    'flux_unit(filtername)': 'Units of the flux measurement',
    'fluxdata(filtername)': 'Detailed flux data for the specified filter',
    'gcrv': 'Radial velocity data from the General Catalogue of Radial Velocities',
    'gen': 'Generic or additional data associated with the object (rarely used)',
    'gj': 'Association with Gliese-Jahreiß (GJ) catalog entries',
    'hbet': 'Measurement related to H-beta line or index',
    'hbet1': 'Additional H-beta line measurement/index',
    'hgam': 'Measurement related to H-gamma line or index',
    'id(opt)': 'An optional or alternative identifier of the object',
    'ids': 'All known identifiers (names) for the object',
    'iras': 'IRAS catalog data or identifier for the object',
    'irc': 'IRC (Infrared Catalogue) data or identifier',
    'iso': 'Data related to ISO (Infrared Space Observatory) measurements',
    'iue': 'Data from IUE (International Ultraviolet Explorer) observations',
    'jp11': 'Additional photometric or index data (rarely used)',
    'link_bibcode': 'Bibcode link for additional references or data',
    'main_id': 'Main (primary) identifier used by SIMBAD for the object',
    'measurements': 'Various measurements compiled for the object',
    'membership': 'Information about the object’s membership in a cluster or group',
    'mesplx': 'Measured parallax data',
    'mespm': 'Measured proper motion data',
    'mk': 'MK spectral classification of the object',
    'morphtype': 'Morphological type classification (often for galaxies)',
    'mt': 'Morphological type data',
    'mt_bibcode': 'Reference for the morphological type data',
    'mt_qual': 'Quality flag for the morphological type',
    'otype': 'Primary object type code assigned by SIMBAD',
    'otype(opt)': 'An optional or alternative object type code',
    'otypes': 'All object type classifications assigned to the object',
    'parallax': 'Parallax measurement of the object',
    'plx': 'Parallax value (synonym or related field to parallax)',
    'plx_bibcode': 'Bibcode for the parallax reference',
    'plx_error': 'Error in the parallax measurement',
    'plx_prec': 'Precision of the parallax measurement',
    'plx_qual': 'Quality flag for the parallax measurement',
    'pm': 'Aggregate proper motion data for the object',
    'pm_bibcode': 'Reference for proper motion data',
    'pm_err_angle': 'Error angle of the proper motion uncertainty ellipse',
    'pm_err_maja': 'Major axis of proper motion error ellipse',
    'pm_err_mina': 'Minor axis of proper motion error ellipse',
    'pm_qual': 'Quality flag for the proper motion data',
    'pmdec': 'Proper motion in Declination',
    'pmdec_prec': 'Precision of the pmDEC measurement',
    'pmra': 'Proper motion in Right Ascension',
    'pmra_prec': 'Precision of the pmRA measurement',
    'pos': 'Positional data (coordinates) of the object',
    'posa': 'Position angle data (often related to dimension measurements)',
    'propermotions': 'Collection of proper motion data from various sources',
    'ra(opt)': 'Right Ascension in an optional format',
    'ra_prec': 'Precision of the RA coordinate',
    'rot': 'Rotational velocity or line-broadening measurement',
    'rv_value': 'Radial velocity value of the object',
    'rvz_bibcode': 'Bibcode for the radial velocity or redshift reference',
    'rvz_error': 'Error in the radial velocity/redshift measurement',
    'rvz_qual': 'Quality flag for the radial velocity/redshift data',
    'rvz_radvel': 'Radial velocity derived from redshift data',
    'rvz_type': 'Type/category of the radial velocity/redshift measurement',
    'rvz_wavelength': 'Wavelength domain for the radial velocity/redshift measurement',
    'sao': 'SAO catalog cross-identification',
    'sp': 'Spectral type assigned to the object',
    'sp_bibcode': 'Reference for the spectral type classification',
    'sp_nature': 'Nature or remarks about the spectral classification',
    'sp_qual': 'Quality flag for the spectral classification',
    'sptype': 'Another spectral type field related to the object',
    'td1': 'TD1 satellite UV measurements',
    'typed_id': 'An identifier with a specific typed format or scheme',
    'ubv': 'UBV photometric data',
    'uvby': 'Strömgren uvby photometric data',
    'uvby1': 'Strömgren uvby+Hβ photometric data',
    'v*': 'Information indicating if the object is a variable star',
    'velocity': 'Velocity data (could be radial or space velocity)',
    'xmm': 'XMM-Newton mission X-ray source cross-identification',
    'z_value': 'Redshift value of the object',
}


B_MK = {
    'Name': 'Star name as published or valid SIMBAD name (Lortet et al.)',
    'Mag': '? Magnitude, see passband in n_Mag',
    'n_Mag': 'Color passband of magnitude (2)',
    'n_SpType': '[+] if spectral type is an MK standard',
    'SpType': 'spectral type (MK, HD, or other)',
    'Remarks': 'Comments (3)',
    'Bibcode': 'Publication Source',
    'RAJ2000': 'Right Ascension (J2000) hour',
    'DEJ2000': 'Declination (J2000) degree',
    'rc': 'Source of coordinates (1)',
    'Simbad': 'VizieR added column, not part of original data',
}

J_AJ_152_62 = {
    'Gal': 'Galaxy name (M31 or M33)',
    'LGGS': 'Star designation in the Local Group Galaxy Survey (LGGS) (JHHMMSS.ss+DDMMSS.s format)',
    'Vmag': '[14.8/20.4] The V-band magnitude',
    'B-V': '[-0.13/0.99] The B-V color index',
    'U-B': '[-1.24/-0.08] The U-B color index',
    'V-R': '[-0.06/1.19] The V-R color index',
    'R-I': '[-0.51/0.77]? The R-I color index',
    'Cwd': 'Index indicating the degree of crowding (I<5%, C=20-80%, or X>80%) (G1)',
    'r_Class': 'References for spectral classification (1)',
    'Class': 'Spectral type classification (mostly cLBV)',
    'pRSG': '[1] 1=Considered as a "post Red SuperGiant (RSG) warm hypergiant" by Humphreys et al. 2015PASP..127..347H',
    'XID': 'Cross-identification',
    'Simbad': 'Simbad column added by the CDS',
}

III_276 = {
    'ID': 'Star Designation (DD NNN)',
    'BD': 'Designation on BD catalog',
    'SAO': '[1,78070]? designation in SAO (Cat. I/131)',
    'RAB1950': '? Right Ascension B1950',
    'DEB1950': '? Declination B1950',
    'Pmag': '? Photographic magnitude',
    'SpT': 'MK spectral classification',
    'u_SpT': 'Uncertainty flag on SpT',
    '_RA.icrs': 'Right ascension (ICRS) (computed by VizieR, not part of the original data)',
    '_DE.icrs': 'Declination (ICRS) (computed by VizieR, not part of the original data)',
}

J_MNRAS_411_263 = {
    'Seq': '[3/19600] Star number',
    'Plot': 'Show the JHK light curves',
    'Jmag': '? Mean J-band magnitude (UKIRT J[98])',
    'Hmag': '? Mean H-band magnitude (UKIRT H[98])',
    'Kmag': 'Mean K-band magnitude (UKIRT K[98])',
    'chi': 'Mean {chi} value from DAOphot',
    'sharp': 'Mean sharpness value from DAOphot (G1)',
    'Jvar': 'Variability index J (2)',
    'Kvar': '[0/1] Kurtosis index K (2)',
    'Lvar': 'Variability index L (2)',
    'Kamp': '? Estimated K-band amplitude',
    'RAJ2000': 'Right Ascension J2000',
    'DEJ2000': 'Declination J2000',
}

III_218 = {
    'Num': 'Running number in the archive',
    'LH_sp': 'FITS file containing the high-resolution (R=42000) spectrum',
    'LL_sp': 'FITS file containing the low-resolution (R=10000) spectrum',
    'Name': 'Object identifier',
    'u_Name': '[?] Uncertain name',
    'Simbad': 'ask the SIMBAD data-base about this object',
    'RAJ2000': '? Right Ascension J2000 (hours)',
    'DEJ2000': '? Declination J2000 (degrees)',
    'SpType': 'Spectral type (from INCA)',
    'HRV': 'Heliocentric radial velocity',
}

III_230 = {
    'Star': 'Star designation ([VGK85] in Simbad)',
    'f_Star': '[*] indicates a note in notes.dat file',
    'RA2000': '? Right ascension (2000), from GSC1.1 (I/220)',
    'DE2000': '? Declination (2000), from GSC1.1 (I/220)',
    'GSC': 'GSC designation (Cat. I/220)',
    'Vmag': '? Photographic V magnitude, rounded to 0.1mag',
    'SpType': 'MK spectral type',
    'Rem': 'Remarks, including cross-identifications',
    '_RA.icrs': 'Right ascension (ICRS) (computed by VizieR, not part of the original data)',
    '_DE.icrs': 'Declination (ICRS) (computed by VizieR, not part of the original data)',
}

I_355_GAIADR3 = {
    'RA_ICRS': 'Right ascension (ICRS) at Ep=2016.0 (ra)',
    'DE_ICRS': 'Declination (ICRS) at Ep=2016.0 (dec)',
    'Source': 'Unique source identifier (unique within a particular Data Release) (source_id)',
    'e_RA_ICRS': 'Standard error of right ascension (ra_error)',
    'e_DE_ICRS': 'Standard error of declination (dec_error)',
    'Plx': '? Parallax (parallax)',
    'e_Plx': '? Standard error of parallax (parallax_error)',
    'PM': '? Total proper motion (pm)',
    'pmRA': '? Proper motion in right ascension direction, pmRA*cosDE (pmra)',
    'e_pmRA': '? Standard error of proper motion in right ascension direction (pmra_error)',
    'pmDE': '? Proper motion in declination direction (pmdec)',
    'e_pmDE': '? Standard error of proper motion in declination direction (pmdec_error)',
    'RUWE': '? Renormalised unit weight error (ruwe)',
    'FG': '? G-band mean flux (phot_g_mean_flux)',
    'e_FG': '? Error on G-band mean flux (phot_g_mean_flux_error)',
    'Gmag': '? G-band mean magnitude (phot_g_mean_mag)',
    'FBP': '? Integrated BP mean flux (phot_bp_mean_flux)',
    'e_FBP': '? Error on the integrated BP mean flux (phot_bp_mean_flux_error)',
    'BPmag': '? Integrated BP mean magnitude (phot_bp_mean_mag)',
    'FRP': '? Integrated RP mean flux (phot_rp_mean_flux)',
    'e_FRP': '? Error on the integrated RP mean flux (phot_rp_mean_flux_error)',
    'RPmag': '? Integrated RP mean magnitude (phot_rp_mean_mag)',
    'BP-RP': '? BP-RP colour (bp_rp)',
    'RV': '? Radial velocity (radial_velocity)',
    'e_RV': '? Radial velocity error (radial_velocity_error)',
    'Vbroad': '? Spectral line broadening parameter (vbroad)',
    'GRVSmag': '? Integrated Grvs magnitude (grvs_mag)',
    'QSO': '[0/1] Flag indicating the availability of additional information in the QSO candidates table (in_qso_candidates)',
    'Gal': '[0/1] Flag indicating the availability of additional information in the galaxy candidates table (in_galaxy_candidates)',
    'NSS': '[0/7] Flag indicating the availability of additional information in the various Non-Single Star tables (non_single_star)',
    'XPcont': '[0/1] Flag indicating the availability of mean BP/RP spectrum in continuous representation for this source (has_xp_continuous)',
    'XPsamp': '[0/1] Flag indicating the availability of mean BP/RP spectrum in sampled form for this source (has_xp_sampled)',
    'RVS': '[0/1] Flag indicating the availability of mean RVS spectrum for this source (has_rvs)',
    'EpochPh': '[0/1] Flag indicating the availability of epoch photometry for this source (has_epoch_photometry)',
    'EpochRV': '[0/1] Flag indicating the availability of epoch radial velocity for this source (has_epoch_rv)',
    'MCMCGSP': '[0/1] Flag indicating the availability of GSP-Phot MCMC samples for this source (has_mcmc_gspphot)',
    'MCMCMSC': '[0/1] Flag indicating the availability of MSC MCMC samples for this source (has_mcmc_msc)',
    'And': '[0/1] Flag indicating that the source is present in the Gaia Andromeda Photometric Survey (GAPS) (in_andromeda_survey)',
    'Teff': '? Effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (teff_gspphot)',
    'logg': '? Surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (logg_gspphot)',
    '__Fe_H_': '? Iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (mh_gspphot)',
    'Dist': '? Distance from GSP-Phot Aeneas best library using BP/RP spectra (distance_gspphot)',
    'A0': '? Monochromatic extinction A_0 at 547.7nm from GSP-Phot Aeneas best library using BP/RP spectra (azero_gspphot)',
    'HIP': '? HIP cross-id number, van Leeuwen, Cat. I/311 (hip_original_ext_source_id)',
    'PS1': '? PS1 cross-id name, Chambers et al., Cat. II/349 (ps1_original_ext_source_id)',
    'SDSS13': '? SDSS name, Albareti et al., 2017ApJS..233...25A (sdss13_ext_source_id)',
    'SKYM2': '? SkyMapperDR2 cross-id name, Onken et al., 2019PASA...36...33O (skym2_original_ext_source_id)',
    'TYC2': 'Tycho-2 cross-id name, Hog et al., Cat. I/259 (tyc2_original_ext_source_id)',
    'URAT1': 'URAT1 name, Zacharias et al., Cat. I/329 (urat1_original_ext_source_id)',
    'AllWISE': 'ALLWISE cross-id name, Cutri et al., Cat. II/328 (allwise_original_ext_source_id)',
    'APASS9': '? APASS9 identification, Henden et al., Cat. II/336 (apass9_original_ext_source_id)',
    'GSC23': 'GSC2.3 cross-id name, Lasker et al., Cat. I/305 (gsc23_original_ext_source_id)',
    'RAVE5': 'RAVE DR5 cross-id name, Kunder et al., Cat. III/279 (rave5_original_ext_source_id)',
    '_2MASS': '2MASS cross-id name, Cutri et al., Cat. II/246 (twomass_original_ext_source_id)',
    'RAVE6': 'RAVE DR6 cross-id name, Steinmetz et al., Cat. III/283 (rave6_original_ext_source_id)',
    'RAJ2000': 'Barycentric right ascension (ICRS) at Ep=2000.0 (added by CDS) (ra2000)',
    'DEJ2000': 'Barycentric declination (ICRS) at Ep=2000.0 (added by CDS) (dec2000)',
}

III_135A = {
    'HD': '[1/272150]+ Henry Draper Catalog (HD) number',
    'DM': 'Durchmusterung identification (1)',
    'RAB1900': 'Hours RA, equinox B1900, epoch 1900.0',
    'DEB1900': 'Degrees Dec, equinox B1900, epoch 1900.0',
    'q_Ptm': '[0/1]? Code for Ptm: 0 = measured, 1 = value inferred from Ptg and spectral type',
    'Ptm': '? Photovisual magnitude (2)',
    'n_Ptm': '[C] "C" if Ptm is combined value with Ptg',
    'q_Ptg': '[0/1]? Code for Ptg: 0 = measured, 1 = value inferred from Ptm and spectral type',
    'Ptg': '? Photographic magnitude (2)',
    'n_Ptg': '[C] "C" if Ptg is combined value for this entry and the following or preceding entry',
    'SpT': 'Spectral type',
    'Int': '[ 0-9B] Photographic intensity of spectrum (3)',
    'Rem': '[DEGMR*] Remarks, see note (4)',
    'Simbad': 'Simbad column added by the CDS',
    '_RA.icrs': 'Right ascension (ICRS) at Epoch=J1900. (computed by VizieR, not part of the original data. The format may include more digits than the original data because of internal accuracy requirements in VizieR and across other CDS services)',
    '_DE.icrs': 'Declination (ICRS) at Epoch=J1900. (computed by VizieR, not part of the original data. The format may include more digits than the original data because of internal accuracy requirements in VizieR and across other CDS services)',
    'Tycho': 'Cross-identification with Tycho-2 (Cat. IV/25)',
}

III_76 = {
    'LS': 'LS number in the form sign, zone, number',
    'Vol': '[1/6] Volume number of published catalogue in which the star is listed.',
    'BD': 'Durchmusterung (BD present in bytes 9-10). Bytes 11-13 contain the zone, and bytes 14-18 the number in the zone.',
    'm_BD': 'Code for duplicity in BD designation',
    'Sp': 'Estimated spectral type.',
    'Pmag': '? Photographic magnitude (see also u_Pmag)',
    'u_Pmag': '[:Vm] Remarks about accuracy, variability, band',
    'RAB1950': 'Right Ascension B1950',
    'DEB1950': 'Declination B1950',
    'u_DEB1950': 'Colon (:) for uncertain coordinates.',
    'Remarks': '*Remarks; an "*" indicates a note detailed in the "notes.dat" file.',
    'AGK2': '[*] indicates an AGK2 star (volumes III and V)',
    '_RA.icrs': 'Right ascension (ICRS) (computed by VizieR, not part of the original data)',
    '_DE.icrs': 'Declination (ICRS) (computed by VizieR, not part of the original data)',
}

III_284 = {
    'm_ID': 'Number of rows for this star (multiple data)',
    'ID': '2MASS-style object name (mainly but not only "2MHHMMSSss+DDMMSSs" or "APHHMMSSss+DDMMSSs") (APOGEE_ID)',
    'Nvis': 'Number of visits for this star (link to allvisits table)',
    'RAJ2000': 'Right ascension (J2000) (RA)',
    'DEJ2000': 'Declination (J2000) (DEC)',
    'SNR': '[-2e-9/4519] Median S/N per pixel in combined frame (at apStar sampling)',
    'SaFlag': 'Flag for star condition taken from bitwise AND of individual visits (ANDFLAG) (G1)',
    'HRV': '[-1629/1658]? Average radial velocity (VHELIO_AVG) (4)',
    'e_HRV': '[0/177]? Uncertainty in VHELIO_AVG from the S/N-weighted individual RVs (VERR)',
    's_HRV': '[0/659]? Scatter of individual visit RVs around average (VSCATTER)',
    'errHRV': '[0/343]? Median of individual visit RV errors (VERR_MED)',
    'f_Teff': '[0/33536] Teff flag for ASCAP analysis (PARAMFLAG1) (G1)',
    'Teff': '[3101/9793]? Teff from ASPCAP analysis of combined spectrum (from PARAM)',
    'e_Teff': '[49/657]? Teff uncertainty (from PARAM_COV) (TEFF_ERR)',
    'f_logg': 'logg flag for ASCAP analysis (PARAMFLAG2) (G1)',
    'logg': '[-0.59/6.55]? logg from ASPCAP analysis of combined spectrum (from PARAM)',
    'e_logg': '[0.01/0.3]? logg uncertainty (from PARAM_COV) (LOGG_ERR)',
    'f_Vmicro': '[0/65540] Vmicro flag for ASCAP analysis (PARAMFLAG3) (G1)',
    'Vmicro': '[0.29/10]? Microturbulent velocity (fit for dwarfs, f(logg) for giants)',
    'Vmacro': '[/12.8]? Macroturbulent velocity (f(logTeff, [M/H]) for giants)',
    'f_Vsini': 'Flag on Vsini for ASCAP analysis (PARAMFLAG8) (G1)',
    'Vsini': '[1.5/96.1]? rotational+macroturbulent velocity (fit for dwarfs)',
    'f__M_H_': 'Metals flag for ASCAP analysis (PARAMFLAG4) (G1)',
    '__M_H_': '[-2.47/0.85]? [M/H] from ASPCAP analysis of combined spectrum (from PARAM) (M_H)',
    'e__M_H_': '[0.004/1.2e+6]? [M/H] uncertainty (from PARAM_COV) (M_H_ERR)',
    'f__a_M_': 'Flag on [a/M] ou [N/Fe]? for ASCAP analysis (PARAMFLAG7) (G1)',
    '__a_M_': '[-0.75/0.9]? [{alpha}/M] from ASPCAP analysis of combined spectrum (from PARAM) (ALPHA_M)',
    'e__a_M_': '[0.0017/4042]? [a/M] uncertainty (from PARAM_COV) (ALPHA_M_ERR)',
    'Chi2': '[/187975]? {Chi}^2^ from ASPCAP fit (ASPCAP_CHI2)',
    'TClass': 'Temperature class of best-fitting spectrum (ASPCAP_CLASS)',
    'AFlag': 'Flag for ASPCAP analysis (ASPCAPFLAG) (G1)',
    'f__C_Fe_': 'Flag on [C/Fe] (C_FE_FLAG) (G1)',
    '__C_Fe_': '[-1.5/1]? [C/Fe] from ASPCAP analysis of combined spectrum (from X_M) (C_FE)',
    'e__C_Fe_': '[0.0014/0.2]? [C/Fe] uncertainty (C_FE_ERR)',
    'f__CI_Fe_': 'Flag on [CI/Fe] (CI_FE_FLAG) (G1)',
    '__CI_Fe_': '[-1.7/1]? [CI/Fe] from ASPCAP analysis of combined spectrum (from X_M) (CI_FE)',
    'e__CI_Fe_': '[0.003/0.2]? [CI/Fe] uncertainty (CI_FE_ERR)',
    'f__N_Fe_': 'Flag on [N/Fe] (N_FE_FLAG) (G1)',
    '__N_Fe_': '[-0.7/1.8]? [N/Fe] from ASPCAP analysis of combined spectrum (from X_M) (N_FE)',
    'e__N_Fe_': '[0.004/0.2]? [N/Fe] uncertainty (N_FE_ERR)',
    'f__O_Fe_': 'Flag on [O/Fe] (O_FE_FLAG) (G1)',
    '__O_Fe_': '[-0.7/0.9]? [O/Fe] from ASPCAP analysis of combined spectrum (from X_M) (O_FE)',
    'e__O_Fe_': '[0.002/0.16]? [O/Fe] uncertainty (O_FE_ERR)',
    'f__Na_Fe_': 'Flag on [Na/Fe] (NA_FE_FLAG) (G1)',
    '__Na_Fe_': '[-2.7/2.2]? [Na/Fe] from ASPCAP analysis of combined spectrum (from X_M) (NA_FE)',
    'e__Na_Fe_': '[0.017/0.2]? [Na/Fe] uncertainty (NA_FE_ERR)',
    'f__Mg_Fe_': 'Flag on [Mg/Fe] (MG_FE_FLAG) (G1)',
    '__Mg_Fe_': '[-0.9/1.2]? [Mg/Fe] from ASPCAP analysis of combined spectrum (from X_M) (MG_FE)',
    'e__Mg_Fe_': '[0.007/0.16]? [Mg/Fe] uncertainty (MG_FE_ERR)',
    'f__Al_Fe_': 'Flag on [Al/Fe] (AL_FE_FLAG) (G1)',
    '__Al_Fe_': '[-2.7/2.2]? [Al/Fe] from ASPCAP analysis of combined spectrum (from X_M) (AL_FE)',
    'e__Al_Fe_': '[0.014/0.2]? [Al/Fe] uncertainty (AL_FE_ERR)',
    'f__Si_Fe_': 'Flag on [Si/Fe] (SI_FE_FLAG) (G1)',
    '__Si_Fe_': '[-1.2/1.4]? [Si/Fe] from ASPCAP analysis of combined spectrum (from X_M) (SI_FE)',
    'e__Si_Fe_': '[0.006/0.17]? [Si/Fe] uncertainty (SI_FE_ERR)',
    'f__P_Fe_': 'Flag on [P/Fe] (P_FE_FLAG) (G1)',
    '__P_Fe_': '[-2.4/2.4]? [P/Fe] from ASPCAP analysis of combined spectrum (from X_M) (P_FE)',
    'e__P_Fe_': '[0.015/0.2]? [P/Fe] uncertainty (P_FE_ERR)',
    'f__S_Fe_': 'Flag on [S/Fe] (S_FE_FLAG) (G1)',
    '__S_Fe_': '[-1.01/1]? [S/Fe] from ASPCAP analysis of combined spectrum (from X_M) (S_FE)',
    'e__S_Fe_': '[0.015/0.2]? [S/Fe] uncertainty (S_FE_ERR)',
    'f__K_Fe_': 'Flag on [K/Fe] (K_FE_FLAG) (G1)',
    '__K_Fe_': '[-2.4/2.3]? [K/Fe] from ASPCAP analysis of combined spectrum (from X_M) (K_FE)',
    'e__K_Fe_': '[0.01/0.2]? [K/Fe] uncertainty (K_FE_ERR)',
    'f__Ca_Fe_': 'Flag on [Ca/Fe] (CA_FE_FLAG) (G1)',
    '__Ca_Fe_': '[-1.21/1]? [Ca/Fe] from ASPCAP analysis of combined spectrum (from X_M) (CA_FE)',
    'e__Ca_Fe_': '[0.004/0.2]? [Ca/Fe] uncertainty (CA_FE_ERR)',
    'f__Ti_Fe_': 'Flag on [Ti/Fe] (TI_FE_FLAG) (G1)',
    '__Ti_Fe_': '[-0.8/1]? [Ti/Fe] from ASPCAP analysis of combined spectrum (from X_M) (TI_FE)',
    'e__Ti_Fe_': '[0.008/0.2]? [Ti/Fe] uncertainty (TI_FE_ERR)',
    'f__TiII_Fe_': 'Flag on [TiII/Fe] (TIII_FE_FLAG) (G1)',
    '__TiII_Fe_': '[-0.95/1]? [TiII/Fe] from ASPCAP analysis of combined spectrum (from X_M) (TIII_FE)',
    'e__TiII_Fe_': '[0.04/0.2]? [TiII/Fe] uncertainty (TIII_FE_ERR)',
    'f__V_Fe_': 'Flag on [V/Fe] (V_FE_FLAG) (G1)',
    '__V_Fe_': '[-2.3/1.9]? [V/Fe] from ASPCAP analysis of combined spectrum (from X_M) (V_FE)',
    'e__V_Fe_': '[0.009/0.2]? [V/Fe] uncertainty (V_FE_ERR)',
    'f__Cr_Fe_': 'Flag on [Cr/Fe] (CR_FE_FLAG) (G1)',
    '__Cr_Fe_': '[-2.7/1.5]? [Cr/Fe] from ASPCAP analysis of combined spectrum (from X_M) (CR_FE)',
    'e__Cr_Fe_': '[0.013/0.2]? [Cr/Fe] uncertainty (CR_FE_ERR)',
    'f__Mn_Fe_': 'Flag on [Mn/Fe] (MN_FE_FLAG) (G1)',
    '__Mn_Fe_': '[-2.2/1.2]? [Mn/Fe] from ASPCAP analysis of combined spectrum (from X_M) (MN_FE)',
    'e__Mn_Fe_': '[0.006/0.2]? [Mn/Fe] uncertainty (MN_FE_ERR)',
    'f__Fe_H_': 'Flag on [Fe/H] (FE_H_FLAG) (G1)',
    '__Fe_H_': '[-2.4/0.9]? [Fe/H] from ASPCAP analysis of combined spectrum (from X_M) (FE_H)',
    'e__Fe_H_': '[0.005/0.2]? [Fe/H] uncertainty (FE_H_ERR)',
    'f__Co_Fe_': 'Flag on [Co/Fe] (CO_FE_FLAG) (G1)',
    '__Co_Fe_': '[-2.6/1.9]? [Co/Fe] from ASPCAP analysis of combined spectrum (from X_M) (CO_FE)',
    'e__Co_Fe_': '[0.01/0.2]? [Co/Fe] uncertainty (CO_FE_ERR)',
    'f__Ni_Fe_': 'Flag on [Ni/Fe] (NI_FE_FLAG) (G1)',
    '__Ni_Fe_': '[-2/1.7]? [Ni/Fe] from ASPCAP analysis of combined spectrum (from X_M) (NI_FE)',
    'e__Ni_Fe_': '[0.006/0.2]? [Ni/Fe] uncertainty (NI_FE_ERR)',
    'f__Cu_Fe_': 'Flag on [Cu/Fe] (CU_FE_FLAG) (G1)',
    '__Cu_Fe_': '[-2.3/1.9]? [Cu/Fe] from ASPCAP analysis of combined spectrum (from X_M) (CU_FE)',
    'e__Cu_Fe_': '[0.015/0.2]? [Cu/Fe] uncertainty (CU_FE_ERR)',
    'f__Ce_Fe_': 'Flag on [Ce/Fe] (CE_FE_FLAG) (G1)',
    '__Ce_Fe_': '[-2.7/2.2]? [Ce/Fe] from ASPCAP analysis of combined spectrum (from X_M) (CE_FE)',
    'e__Ce_Fe_': '[0.038/0.2]? [Ce/Fe] uncertainty (CE_FE_ERR)',
    'Gaia': '? Gaia DR2 identifier (GAIA_SOURCE_ID)',
    'Sp': 'Display the IR spectrum in SDSS SAS',
}

III_47 = {
    'ID': 'Star id',
    'RA1900': 'Right ascension, equinox 1900',
    'u_RA1900': '[:] RA approx flag',
    'DE1900': 'Declination, equinox 1900',
    'u_DE1900': '[:] Dec approx flag',
    'n_Mag1': '[ABC*(] Note flag concerning Mag1',
    'Mag1': '? Photoelectric V magnitude (see also n_Mag1 and n_Mag2)',
    'SpType': 'Spectral type',
    'RVel': '? Radial Velocity',
    'u_RVel': '[)*:9] Uncertainty note on RVel',
    'q_RVel': '[ABCDE? 3] Quality of Radial Velocity',
    'Npl': '? Plate count',
    'u_Npl': '[:+?)] Note concerning Nplates',
    'ObsCode': 'Observe Code',
    'Flags': '[VMD ] Variability and multiplicity flags',
    'SimbadName': 'Simbad column added by the CDS',
    '_RA.icrs': 'Right ascension (ICRS) (computed by VizieR, not part of the original data)',
    '_DE.icrs': 'Declination (ICRS) (computed by VizieR, not part of the original data)',
}

